### ISSUE TITLE
Issue with number precision

### ISSUE THREAD

**Issue by leptonyu** [oracle/odpi#68] opened 2018-07-03 05:03 UTC
`odpic-raw` happens to truncate double to lower precision when testing query on [chinook db](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Oracle.sql) 

```SQL
select avg(milliseconds) from track;
````

Results

```
cx_Oracle  => 393599.2121039109
odpic-raw => 393599.2121039109188131988048553466796875

should be (Sql Developer and Intellij Idea DataSource)
393599.2121039109334855837853268626891236
```

It shows `ODPI-C` might truncate double values, please help. Thanks.

origin issue on leptonyu/odpic-raw#11

**Comment by cjbj** [comment] 2018-07-03 06:00
So everyone's testing the same thing, can you give the DDL and data, and the platform info?

**Comment by leptonyu** [comment] 2018-07-03 06:15
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

**Comment by cjbj** [comment] 2018-07-03 06:17
@leptonyu can you share the CREATE TABLE statement?  And, for completeness, what Oracle client library version are you using?

**Comment by leptonyu** [comment] 2018-07-03 06:30
`CREATE TABLE` statement are all in [DDL File](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Oracle.sql).


instantclient-basic-macos.x64-12.2.0.1.0-2.zip
instantclient-sdk-macos.x64-12.2.0.1.0-2.zip
instantclient-sqlplus-macos.x64-12.2.0.1.0-2.zip
and ODPI-C 2.4.0

**Comment by kubo** [comment] 2018-07-03 08:09
Does odpic-raw use `DPI_NATIVE_TYPE_DOUBLE` to fetch number columns? If so, it is by design. The significant decimal digits of double is 15 or so. All results you posted are same within the significant digits.

In [Wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64):
> The 53-bit significand precision gives from 15 to 17 significant decimal digits precision.

The following @mulderr's [comment](https://github.com/leptonyu/odpic-raw/issues/11#issue-335182920) seems to get straight to the point. There is no way to get a full precision `NUMBER` except using `DPI_NATIVE_TYPE_BYTES`.
> it looks like the `FromDataField` instance for `Decimal` is missing a case for reading a full precision `NUMBER` from `DataNumBytes` which I would expect to happen here

**Comment by leptonyu** [comment] 2018-07-03 09:01
@kubo I did not change the default `dpiNativeTypeNum` type when fetching number columns, `ODPI-C` use `DPI_NATIVE_TYPE_DOUBLE ` as default.

```
Data_DataTypeInfo {oracleTypeNum = OracleTypeNumber, defaultNativeTypeNum = NativeTypeDouble, ociTypeCode = 2, dbSizeInBytes = 0, clientSizeInBytes = 0, sizeInChars = 0, precision = 0, scale = -127, fsPrecision = 0, objectType = 0x0000000000000000}
```

 [dpiStmt_getQueryValue](https://oracle.github.io/odpi/doc/public_functions/dpiStmt.html#c.dpiStmt_getQueryValue) said I need to use [dpiStmt_defineValue](https://oracle.github.io/odpi/doc/public_functions/dpiStmt.html#c.dpiStmt_defineValue) to override default type. 

so, in what circumstances could I fetch number columns as `DPI_NATIVE_TYPE_BYTES` by default? or I should always defineValue before fetching it?

**Comment by leptonyu** [comment] 2018-07-03 12:36
I have fix this, by overriding defaultNativeTypeNum as `DPI_NATIVE_TYPE_BYTES` using [dpiStmt_defineValue](https://oracle.github.io/odpi/doc/public_functions/dpiStmt.html#c.dpiStmt_defineValue). 

But I think it's better for `ODPI-C` to set defaultNativeTypeNum as `DPI_NATIVE_TYPE_BYTES` for `DPI_ORACLE_TYPE_NUMBER`.

**Comment by anthony-tuininga** [comment] 2018-07-03 14:31
As @kubo noted, double only has about 15 digits of precision so if you need something better than that you will need to use DPI_NATIVE_TYPE_BYTES. Most people, however, do not need that level of precision and prefer to use native types for greater performance, so I don't think the default type should be changed. The "issue" with double and conversion to decimal is a common theme, but unfortunately it is also one that cannot be solved!

The node-oracledb driver has this [documentation](https://github.com/oracle/node-oracledb/blob/master/doc/api.md#-9162-fetching-numbers). Would adding something similar to the ODPI-C documentation help?

**Comment by leptonyu** [comment] 2018-07-03 15:04
@anthony-tuininga yes, please add some description about this.


btw, is there any detailed documents about [dpiTimestamp](https://oracle.github.io/odpi/doc/public_structs/dpiTimestamp.html) and it's conversion with timezone? I was also confused the timestamp values and timezone offset.

**Comment by anthony-tuininga** [comment] 2018-07-03 15:16
Ok. I'll add some information about floating point numbers in the documentation.

The information you referenced in your question is the information that is available. What are you finding confusing?

**Comment by leptonyu** [comment] 2018-07-04 08:09
`DPI_ORACLE_TYPE_TIMESTAMP` 
`DPI_ORACLE_TYPE_TIMESTAMP_LTZ` 
`DPI_ORACLE_TYPE_TIMESTAMP_TZ` 
what timestamp part of `dpiTimestamp` stand for? localtime or utctime? it shows all the three type of timestamp use localtime. am i right?

**Comment by cjbj** [comment] 2018-07-05 23:51
I'll reopen this as a reminder to @anthony-tuininga about the changes suggested by @kubo

**Comment by anthony-tuininga** [comment] 2018-07-24 02:52
Changes implemented so closing.

**Closed by anthony-tuininga** 2018-07-24 02:52 UTC
Labels: enhancement
